-- สร้างโดย blender/mesh_export.py — EmberCrystal (โมเดลจริงจาก Blender, ประกอบเป็น EditableMesh ตอนเล่น)
return {
	Name = "EmberCrystal",
	Height = 9.000,
	Palette = table.concat({
			"QAACAAIA/3spPgAAAAACAP97KT4AAAAA"
		}),
	Parts = {
		{
			Name = "Glow_ff7828",
			Attach = "Body",
			Center = {0.0000, 4.5000, 0.0000},
			Size = {13.1430, 9.0000, 11.7941},
			Color = {1.000, 0.482, 0.161},
			Glow = {1.000, 0.471, 0.157},
			Mesh = table.concat({
			"DQABABIAFgDG8ZAFbRUd9pQR5A5U5nAHZP4p7pQR4v6P9MAG9+gN+JQR/u86DpEFk+rjCZQRHPGsGcAGnAHXEZQRHgFxC8AGCRfzB5QRAhAAAGzuAAAABACAnT8xo0U0qEfGqETDB0SVCj+SYz/PX0PNAH8AWkQ8+URr9j9usKvOTqo0qqokAqmj/qldVanaAAABAAMAAAAAAAAAAAAAAAAAAAADAAIAAAAAAAAAAQABAAEAAgADAAUAAAAAAAAAAgACAAIAAgAFAAQAAAAAAAAAAwADAAMABAAFAAcAAAAAAAAABAAEAAQABAAHAAYAAAAAAAAABQAFAAUABgAHAAkAAAAAAAAABgAGAAYABgAJAAgAAAAAAAAABwAHAAcABQADAAEAAAAAAAAACAAIAAgAAQALAAkAAAAAAAAACAAIAAgACQAHAAUAAAAAAAAACAAIAAgAAQAJAAUAAAAAAAAACAAIAAgACAAJAAsAAAAAAAAACQAJAAkACAALAAoAAAAAAAAACQAJAAkACgALAAEAAAAAAAAACgAKAAoACgABAAAAAAAAAAAACwALAAsAAgAEAAwAAAAAAAAADAAMAAwACAAKAAwAAAAAAAAADQANAA0AAAACAAwAAAAAAAAADgAOAA4ABAAGAAwAAAAAAAAADwAPAA8ACgAAAAwAAAAAAAAAEAAQABAABgAIAAwAAAAAAAAAEQARABEA"
		}),
		},
	},
}
