-- สร้างโดย blender/mesh_export.py — Flowers (โมเดลจริงจาก Blender, ประกอบเป็น EditableMesh ตอนเล่น)
return {
	Name = "Flowers",
	Height = 2.350,
	Palette = table.concat({
			"QAACAAIASos5AgD21Ys8AAAAAAIASos5AgD21Ys8AAAAAA=="
		}),
	Parts = {
		{
			Name = "Main",
			Attach = "Body",
			Center = {0.0000, 1.1500, 0.0000},
			Size = {1.9836, 2.4000, 2.2574},
			Color = {0.610, 0.683, 0.376},
			Mesh = table.concat({
			"hgACAB4ATACs/1D7igGs/1D7AABX/lD7xQCs/1D7dv5X/lD7O/8B/VD7AAA9/JD/l/vL/lr+8Pwg/Fr+ev4g/Fr+ev7L/lr+8Pw9/JD/l/sB/VD7AABX/lD7xQAg/Fr+hgGs/1D7igHL/lr+EAMg/Fr+hgFX/lD7xQAB/VD7AACs/1D7igHL/lr+EAOs/1D7dv5X/lD7O//L/lr+8PwB/VD7AAAg/Fr+ev7L/lr+8PxX/lD7O/+s/1D7dv4B/VD7AAAg/Fr+ev6s/1D7dv5uAVr+dv6s/1D7AABuAVr+igGs/1D7igGs/1D7AABuAVr+dv6s/1D7dv5uAVr+igGs/1D7igHL/lr+EAM9/JD/aQQg/Fr+hgEg/Fr+hgE9/JD/aQTL/lr+EANuAVr+dv7gA5D/AABuAVr+igFuAVr+igHgA5D/AABuAVr+dv6s/1D7igFX/lD7xQAB/1X/xQAB/VD7AACs/VX/AABX/lX/YwAB/VD7AABX/lD7O/+s/VX/AACs/1D7dv4B/1X/O/9X/lX/nf+s/1D7dv6s/1D7AAAB/1X/O/8B/1X/AACs/1D7igEB/1X/xQBY/VX/yP5Y/bAEyP5Y/VX/OAFY/bAEOAGQ/DMEAf6Q/DME/wFY/VX/yP5Y/VX/OAFY/VX/yP6Q/DME/wGQ/DMEAf5Y/VX/OAHH/7AEyP7H/7AEOAFY/bAEyP5Y/bAEOAHH/1X/OAFY/VX/OAGPADME/wGQ/DME/wGPADME/wFY/VX/OAHH/1X/OAGQ/DME/wHH/1X/OAFY/VX/OAHH/7AEOAFY/bAEOAHH/7AEyP7H/1X/yP7H/7AEOAHH/1X/OAHH/1X/yP4B/1X/xQDH/1X/OAFY/VX/OAFX/lX/YwCs/VX/AAAB/1X/O/9Y/VX/yP4B/1X/AABX/lX/nf+PADMEAf7H/1X/yP6PADME/wHH/1X/OAGPADME/wHH/1X/yP6PADMEAf7H/1X/OAFY/VX/yP7H/1X/yP6Q/DMEAf6PADMEAf6Q/DMEAf7H/1X/yP5Y/VX/yP6PADMEAf5Y/VX/yP7H/1X/yP5Y/bAEyP7H/7AEyP4ABACAAAwAgACBABxyMeSOzzdAocnAXzdAX8nAoZJAAG7AABxyz+SOMchyADiOAMEKbgAAAMEKkn0VAIEAAIPsAH0UAAB/AADsfQAUgwAAf38AAH3sAIMUAADsgwAUfQAAgQIAAQAAAAAAAAAAAAAAAAAAAAEAAgADAAAAAAAAAAAAAAAAAAMAAgAEAAAAAAAAAAAAAAAAAAQAAgAFAAAAAAAAAAAAAAAAAAgABwAGAAAAAAAAAAEAAQABAAsACgAJAAAAAAAAAAIAAgACAA4ADQAMAAAAAAAAAAMAAwADAA0ADgAPAAAAAAAAAAMAAwADAA8ADgAQAAAAAAAAAAMAAwADABMAEgARAAAAAAAAAAQABAAEABQAEQASAAAAAAAAAAQABAAEABUAEQAUAAAAAAAAAAQABAAEABgAFwAWAAAAAAAAAAUABQAFABcAGAAZAAAAAAAAAAUABQAFABkAGAAaAAAAAAAAAAUABQAFAB0AHAAbAAAAAAAAAAYABgAGAB4AGwAcAAAAAAAAAAYABgAGAB8AGwAeAAAAAAAAAAYABgAGACIAIQAgAAAAAAAAAAcABwAHACEAIgAjAAAAAAAAAAcABwAHACMAIgAkAAAAAAAAAAcABwAHACcAJgAlAAAAAAAAAAgACAAIACgAJQAmAAAAAAAAAAgACAAIACkAJQAoAAAAAAAAAAgACAAIACwAKwAqAAAAAAAAAAkACQAJAC8ALgAtAAAAAAAAAAoACgAKADIAMQAwAAAAAAAAAAsACwALADUANAAzAAAAAAAAAAwADAAMADgANwA2AAAAAAAAAA0ADQANADcAOAA5AAAAAAAAAA0ADQANADkAOAA6AAAAAAAAAA0ADQANADoAOAA7AAAAAAAAAA4ADgAOAD4APQA8AAAAAAAAAA8A",
			"DwAPAD0APgA/AAAAAAAAAA8ADwAPAD8APgBAAAAAAAAAAA8ADwAPAEAAPgBBAAAAAAAAAAAAAAAAAEQAQwBCAAAAAAAAABAAEAAQAEMARABFAAAAAAAAABAAEAAQAEMARQBGAAAAAAAAABAAEAAQAEYARQBHAAAAAAAAABAAEAAQAEoASQBIAAEAAQABABEAEQARAEkASgBLAAEAAQABABEAEQARAE4ATQBMAAEAAQABABIAEgASAE0ATgBPAAEAAQABABIAEgASAFIAUQBQAAEAAQABABMAEwATAFMAUABRAAEAAQABABMAEwATAFYAVQBUAAEAAQABABQAFAAUAFUAVgBXAAEAAQABABQAFAAUAFoAWQBYAAEAAQABABUAFQAVAFkAWgBbAAEAAQABABUAFQAVAF4AXQBcAAEAAQABABYAFgAWAF8AXABdAAEAAQABABYAFgAWAGIAYQBgAAEAAQABABcAFwAXAGEAYgBjAAEAAQABABcAFwAXAGYAZQBkAAEAAQABABgAGAAYAGUAZgBnAAEAAQABABgAGAAYAGoAaQBoAAEAAQABAAAAAAAAAGkAagBrAAEAAQABAAAAAAAAAGkAawBsAAEAAQABAAAAAAAAAGwAawBtAAEAAQABAAAAAAAAAG4AaABpAAEAAQABAAAAAAAAAGgAbgBvAAEAAQABAAAAAAAAAG8AbQBrAAEAAQABAAAAAAAAAG4AaQBwAAEAAQABAA4ADgAOAG8AbgBxAAEAAQABAAAAAAAAAG8AcQBtAAEAAQABAAAAAAAAAHQAcwByAAEAAQABABkAGQAZAHMAdAB1AAEAAQABABkAGQAZAHgAdwB2AAEAAQABABoAGgAaAHkAdgB3AAEAAQABABoAGgAaAHwAewB6AAEAAQABABsAGwAbAHsAfAB9AAEAAQABABsAGwAbAIAAfwB+AAEAAQABABwAHAAcAIEAfgB/AAEAAQABABwAHAAcAIQAgwCCAAEAAQABAB0AHQAdAIMAhACFAAEAAQABAB0AHQAdAA=="
		}),
		},
	},
}
