-- สร้างโดย blender/mesh_export.py — GaleCrystal (โมเดลจริงจาก Blender, ประกอบเป็น EditableMesh ตอนเล่น)
return {
	Name = "GaleCrystal",
	Height = 9.000,
	Palette = table.concat({
			"QAACAAIA3u7/PgAAAAACAN7u/z4AAAAA"
		}),
	Parts = {
		{
			Name = "Glow_dcecff",
			Attach = "Body",
			Center = {0.0000, 4.5000, 0.0000},
			Size = {5.4502, 9.0000, 3.0387},
			Color = {0.871, 0.933, 1.000},
			Glow = {0.863, 0.925, 1.000},
			Mesh = table.concat({
			"GAABABoALAARBWzu9vxlBWP2EfqlCh308vxlBZ0JEfoRBZQR9vylCuML8vwRBWzuCgOlCh30DgNlBWP27wURBZQRCgNlBZ0J7wWlCuMLDgPv+mzu9vxb9R308vyb+mP2Efrv+pQR9vyb+p0JEfpb9eML8vzv+mzuCgOb+mP27wVb9R30DgPv+pQRCgNb9eMLDgOb+p0J7wUABACAwwCRANV3K9Zw1daQACuJACt31SpwKyqQAACBAAB/Kypw1SqQ1dZwPQBvANWJW6cAfwAAW1kAwwBvpacApVkAAIEAgQAAK9aQPQCRAH8ADgANABEAAAAAAAAAAAAAAAAADgARABAAAAAAAAAAAAAAAAAAEgAGAAgAAAAAAAAAAQABAAEAEgAIABMAAAAAAAAAAQABAAEACAAGAAcAAAAAAAAAAgACAAIADgAMAA0AAAAAAAAAAwADAAMADwAEAAMAAAAAAAAABAAEAAQADwADABAAAAAAAAAABAAEAAQACQAVABcAAAAAAAAABQAFAAUACQAXAAoAAAAAAAAABQAFAAUAFwAVABYAAAAAAAAABgAGAAYAAwAEAAUAAAAAAAAABwAHAAcAAQAOABAAAAAAAAAACAAIAAgAAQAQAAMAAAAAAAAACAAIAAgAEwAIAAoAAAAAAAAACQAJAAkAEwAKABcAAAAAAAAACQAJAAkACQAKAAsAAAAAAAAACgAKAAoADwAQABEAAAAAAAAACwALAAsAEgATABQAAAAAAAAADAAMAAwACAAHAAsAAAAAAAAADQANAA0ACAALAAoAAAAAAAAADQANAA0AAAAMAA4AAAAAAAAADgAOAA4AAAAOAAEAAAAAAAAADgAOAA4AAgAHAAYAAAAAAAAADwAPAA8AAgAGAAAAAAAAAAAADwAPAA8ABwACAAUAAAAAAAAAEAAQABAABwAFAAsAAAAAAAAAEAAQABAABAAJAAsAAAAAAAAAEQARABEABAALAAUAAAAAAAAAEQARABEAFAATABcAAAAAAAAAEgASABIAFAAXABYAAAAAAAAAEgASABIADAASABQAAAAAAAAAEwATABMADAAUAA0AAAAAAAAAEwATABMAFQAPABEAAAAAAAAAFAAUABQAFQARABYAAAAAAAAAFAAUABQABgASAAwAAAAAAAAAFQAVABUABgAMAAAAAAAAAAAAFQAVABUADQAUABYAAAAAAAAAFgAWABYADQAWABEAAAAAAAAAFgAWABYAAAABAAIAAAAAAAAAFwAXABcAAgABAAMAAAAAAAAAGAAYABgAAgADAAUAAAAAAAAAGAAYABgAFQAJAAQAAAAAAAAAGQAZABkAFQAEAA8AAAAAAAAAGQAZABkA"
		}),
		},
	},
}
