-- สร้างโดย blender/mesh_export.py — SeaRock (โมเดลจริงจาก Blender, ประกอบเป็น EditableMesh ตอนเล่น)
return {
	Name = "SeaRock",
	Height = 9.950,
	Palette = table.concat({
			"QAACAAIA5sWcAgD2//8CAEqUOToAAAAAAgDmxZwCAPb//wIASpQ5OgAAAAA="
		}),
	Parts = {
		{
			Name = "Main",
			Attach = "Body",
			Center = {0.0000, 4.9500, 0.0000},
			Size = {5.8267, 10.0000, 5.5753},
			Color = {0.815, 0.784, 0.622},
			Mesh = table.concat({
			"TAADAA4AJQBP+njs5Aqf9HjsmweW/LEMiQYs+bEMkAQ4/bEMfP1EAbEMd/nC/ogTIv6CAYgTZvthC3jsmwdP+njs5ArUBrEMkASW/LEMiQa1AbEMjAUcAnjsHPVhC3jsd/pEAbEMd/nUBrEMrvws+bEMgAEs+bEMkASf9HjsgAKf9Hjsmwc4/bEMfP3C/ogTIv61AbEMjAXPAYgTnQPUBrEMrvzUBrEMkARKBYgTlf1KBYgT8gKf9HjsgAIcAnjsHPUs+bEMgAFEAbEMd/k4/bEMfP3UBrEMkAS1AbEMjAVKBYgT8gLPAYgTnQNEAbEMd/nUBrEMrvyCAYgTZvtKBYgTlf1hC3jsd/phC3jsmwfUBrEMrvzUBrEMkARhC3jsmwdhC3jsd/pP+njs5AocAnjsHPVP+njs5AphC3jsd/qf9HjsgAJP+njs5AocAnjsHPWf9HjsmwdP+njs5Aqf9HjsgALUBrEMrvzUBrEMkAREAbEMd/m1AbEMjAVEAbEMd/nUBrEMkAQ4/bEMfP21AbEMjAVKBYgTlf1KBYgT8gKCAYgTZvvPAYgTnQPC/ogTIv61AbEMjAWW/LEMiQY4/bEMfP0s+bEMgAEs+bEMkAQABACAAAwAgAAUAIDBE22pHKgYD3wAgQA/EJOCEgCSEz18HACnCqYAAAAXIng+HJV+EgAAfwACAAEAAAAAAAAAAAAAAAAAAAABAAIAAwAAAAAAAAAAAAAAAAAGAAUABAAAAAAAAAABAAEAAQAFAAYABwAAAAAAAAABAAEAAQAKAAkACAAAAAAAAAACAAIAAgAJAAoACwAAAAAAAAACAAIAAgALAAoADAAAAAAAAAADAAMAAwAPAA4ADQAAAAAAAAAEAAQABAAOAA8AEAAAAAAAAAAEAAQABAATABIAEQAAAAAAAAAFAAUABQASABMAFAAAAAAAAAAFAAUABQAXABYAFQAAAAAAAAAGAAYABgAWABcAGAAAAAAAAAAGAAYABgAbABoAGQAAAAAAAAAHAAcABwAaABsAHAAAAAAAAAAHAAcABwAfAB4AHQAAAAAAAAAIAAgACAAeAB8AIAAAAAAAAAAIAAgACAAgAB8AIQAAAAAAAAAJAAkACQAkACMAIgAAAAAAAAAKAAoACgAjACQAJQAAAAAAAAAKAAoACgAoACcAJgAAAAAAAAALAAsACwAnACgAKQAAAAAAAAALAAsACwAsACsAKgAAAAAAAAAMAAwADAArACwALQAAAAAAAAAMAAwADAAwAC8ALgABAAEAAQADAAMAAwAzADIAMQABAAEAAQADAAMAAwA2ADUANAABAAEAAQADAAMAAwA5ADgANwABAAEAAQADAAMAAwA8ADsAOgABAAEAAQANAA0ADQA/AD4APQABAAEAAQANAA0ADQBBAD4AQAABAAEAAQANAA0ADQBEAEMAQgACAAIAAgANAA0ADQBDAEQARQACAAIAAgANAA0ADQBFAEQARgACAAIAAgANAA0ADQBJAEgARwACAAIAAgANAA0ADQBIAEkASgACAAIAAgANAA0ADQBIAEoASwACAAIAAgANAA0ADQA="
		}),
		},
	},
}
